#!/bin/bash -x
echo "Welcome to Employee Wage Computation Program on Master Branch"
ISFULLTIME=1
ISPARTTIME=2
WAGES_PER_HOUR=20
TOTAL_WAGES=0
WORKING_DAYS=20
TOTAL_WORKING_HOURS=100
count=0
function wages(){
for (( i=1;i<=$1;i++ ))
do
	RAND_CHECK=$((RANDOM%3+1))
	if [ $count -ne $2 ]
	then
		case $RAND_CHECK in
			$ISFULLTIME)
			DAILY_EMPLOY_WAGES=$(($WAGES_PER_HOUR*8))
			echo "DAILY WAGES"$DAILY_EMPLOY_WAGES
			TOTAL_WAGES=$(($TOTAL_WAGES+$DAILY_EMPLOY_WAGES));;
			$ISPARTTIME)
			DAILY_EMPLOY_WAGES_PART_TIME=$(($WAGES_PER_HOUR*4))
			echo "DAILY WAGES"$DAILY_EMPLOY_WAGES_PART_TIME
			TOTAL_WAGES=$(($TOTAL_WAGES+$DAILY_EMPLOY_WAGES_PART_TIME));;
			*);;
		esac
	else
		break
	fi
done
}
wages  $WORKING_DAYS $TOTAL_WORKING_HOURS
echo "TOTAL WAGES :$TOTAL_WAGES"
#echo "WAGES FOR PARTIME::$DAILY_EMPLOY_WAGES_PART_TIME"
