#!/bin/bash -x
echo "Welcome to Employee Wage Computation Program on Master Branch"
ISFULLTIME=1
ISPARTTIME=2
WAGES_PER_HOUR=20
DAILY_EMPLOY_WAGES=0
DAILY_EMPLOY_WAGES_PART_TIME=0

WORKING_DAYS=20
for (( i=1;i<=$WORKING_DAYS;i++ ))
do
	RAND_CHECK=$((RANDOM%3+1))
	case $RAND_CHECK in
		$ISFULLTIME )DAILY_EMPLOY_WAGES=$(($DAILY_EMPLOY_WAGES+$(($WAGES_PER_HOUR*8))))
		;;

		$ISPARTTIME )DAILY_EMPLOY_WAGES_PART_TIME=$(($DAILY_EMPLOY_WAGES_PART_TIME+$(($WAGES_PER_HOUR*4))))
		;;
		*);;
	esac
done
echo "WAGES FOR FULLTIME :$DAILY_EMPLOY_WAGES"
echo "WAGES FOR PARTIME::$DAILY_EMPLOY_WAGES_PART_TIME"
